Repository ticket-together/ticket-server, pull requests merged in 2022-09, with the labels that each got.

#103 ✨ prod id로 팟 목록 조회
  src/main/java/com/tickettogether/domain/parts/controller/PartsController.java
  src/main/java/com/tickettogether/domain/parts/domain/Parts.java
  src/main/java/com/tickettogether/domain/parts/dto/PartsDto.java
  src/main/java/com/tickettogether/domain/parts/dto/PartsResponseMessage.java
  src/main/java/com/tickettogether/domain/parts/repository/MemberPartsRepository.java
  src/main/java/com/tickettogether/domain/parts/repository/PartsRepository.java
  src/main/java/com/tickettogether/domain/parts/service/MemberPartsService.java
  src/main/java/com/tickettogether/domain/parts/service/MemberPartsServiceImpl.java
Labels: 🕹 기능

#110 :recycle: 입장 시각 이후의 채팅 목록만 보여주도록 변경
  src/main/java/com/tickettogether/domain/chat/controller/ChatRoomController.java
  src/main/java/com/tickettogether/domain/chat/controller/StompChatController.java
  src/main/java/com/tickettogether/domain/chat/dto/ChatDto.java
  src/main/java/com/tickettogether/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/tickettogether/domain/chat/service/ChatRoomService.java
  src/main/java/com/tickettogether/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/tickettogether/global/config/redis/util/RedisUtil.java
  src/main/resources/templates/Room.html
Labels: 🛠 리팩토링

#114 :zap: ChatMessage 시간 필드에 인덱스 적용
  src/main/java/com/tickettogether/domain/chat/controller/StompChatController.java
  src/main/java/com/tickettogether/domain/chat/domain/ChatMessage.java
  src/main/java/com/tickettogether/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/tickettogether/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/tickettogether/global/common/Constant.java
  src/main/java/com/tickettogether/global/dto/PageDto.java
Labels: 🛠 리팩토링

#136 🩹 OAuth 사용자 정보 수정
  src/main/java/com/tickettogether/domain/chat/controller/ChatRoomController.java
  src/main/java/com/tickettogether/domain/chat/dto/ChatDto.java
  src/main/java/com/tickettogether/domain/member/domain/Member.java
  src/main/java/com/tickettogether/domain/member/dto/MemberDto.java
  src/main/java/com/tickettogether/domain/member/service/MemberServiceImpl.java
  src/main/java/com/tickettogether/global/config/security/oauth/dto/KakaoOAuthAttributes.java
  src/main/java/com/tickettogether/global/config/security/oauth/dto/OAuthAttributes.java
  src/main/java/com/tickettogether/global/config/security/oauth/service/CustomOAuth2UserService.java
Labels: 🛠 리팩토링

#137 :sparkles: 키워드 수정 기능 추가
  src/main/java/com/tickettogether/domain/member/controller/LoginController.java
  src/main/java/com/tickettogether/domain/member/controller/MemberController.java
  src/main/java/com/tickettogether/domain/member/domain/Member.java
  src/main/java/com/tickettogether/domain/member/domain/MemberKeyword.java
  src/main/java/com/tickettogether/domain/member/dto/MemberDto.java
  src/main/java/com/tickettogether/domain/member/dto/MemberResponseMessage.java
  src/main/java/com/tickettogether/domain/member/service/MemberServiceImpl.java
Labels: 🕹 기능

#139 :recycle: 로그인 유저 어노테이션 기반 리팩토링
  src/main/java/com/tickettogether/domain/member/controller/MemberController.java
  src/main/java/com/tickettogether/global/config/security/CustomUserDetailsService.java
  src/main/java/com/tickettogether/global/config/security/SecurityConfig.java
  src/main/java/com/tickettogether/global/config/security/UserPrincipal.java
  src/main/java/com/tickettogether/global/config/security/annotation/CustomArgumentResolver.java
  src/main/java/com/tickettogether/global/config/security/annotation/LoginUser.java
  src/main/java/com/tickettogether/global/config/security/jwt/filter/TokenAuthenticationFilter.java
  src/main/java/com/tickettogether/global/config/security/jwt/service/AuthService.java
  src/main/java/com/tickettogether/global/config/security/oauth/dto/OAuthAttributes.java
  src/main/java/com/tickettogether/global/config/security/oauth/handler/MyOauth2SuccessHandler.java
  src/main/java/com/tickettogether/global/config/web/WebMvcConfig.java
Labels: 🛠 리팩토링

#143 :bug: JSON 배열 요청 데이터 역직렬화 에러
  src/main/java/com/tickettogether/domain/member/dto/MemberDto.java
Labels: 🐛 버그

#149 :recycle: 사용자 정보 저장 필드 변경
  src/main/java/com/tickettogether/domain/member/domain/Member.java
  src/main/java/com/tickettogether/domain/member/dto/MemberDto.java
  src/main/java/com/tickettogether/domain/member/service/MemberServiceImpl.java
  src/main/java/com/tickettogether/global/config/security/oauth/dto/KakaoOAuthAttributes.java
  src/main/java/com/tickettogether/global/config/security/oauth/dto/OAuthAttributes.java
  src/main/java/com/tickettogether/global/config/security/oauth/service/CustomOAuth2UserService.java
Labels: 🛠 리팩토링

#152 🐛 expired 예외 처리
  src/main/java/com/tickettogether/global/config/security/exception/TokenExpiredException.java
  src/main/java/com/tickettogether/global/config/security/jwt/filter/TokenAuthenticationFilter.java
  src/main/java/com/tickettogether/global/config/security/jwt/token/AuthToken.java
  src/main/java/com/tickettogether/global/config/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/tickettogether/global/error/BaseExceptionHandlerFilter.java
  src/main/java/com/tickettogether/global/error/ErrorCode.java
Labels: 🐛 버그

#151 :bug: 토큰 만료 예외 처리 수정
  src/main/java/com/tickettogether/global/config/security/exception/TokenBlackListException.java
  src/main/java/com/tickettogether/global/config/security/exception/TokenExpiredException.java
  src/main/java/com/tickettogether/global/config/security/jwt/filter/TokenAuthenticationFilter.java
  src/main/java/com/tickettogether/global/config/security/jwt/token/AuthToken.java
  src/main/java/com/tickettogether/global/config/security/jwt/token/AuthTokenProvider.java
  src/main/java/com/tickettogether/global/config/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/tickettogether/global/error/BaseExceptionHandlerFilter.java
  src/main/java/com/tickettogether/global/error/ErrorCode.java
Labels: 🐛 버그

#173 ♻️ 팟 삭제시 예외처리 추가
  src/main/java/com/tickettogether/domain/parts/exception/PartsMemberExistedException.java
  src/main/java/com/tickettogether/domain/parts/service/MemberPartsServiceImpl.java
  src/main/java/com/tickettogether/global/error/ErrorCode.java
Labels: 🛠 리팩토링

#178 :bug: 필터 대신 Cors Registry로 변경
  src/main/java/com/tickettogether/global/config/security/SecurityConfig.java
  src/main/java/com/tickettogether/global/config/web/WebMvcConfig.java
Labels: 🐛 버그

#182 :recycle: 채팅 로그인 연동 및 에러 해결
  src/main/java/com/tickettogether/domain/chat/config/WebSocketConfig.java
  src/main/java/com/tickettogether/domain/chat/controller/ChatRoomController.java
  src/main/java/com/tickettogether/domain/chat/controller/StompChatController.java
  src/main/java/com/tickettogether/domain/chat/domain/ChatRoom.java
  src/main/java/com/tickettogether/domain/chat/dto/ChatDto.java
  src/main/java/com/tickettogether/domain/chat/interceptor/AuthenticationChannelInterceptor.java
  src/main/java/com/tickettogether/domain/chat/service/ChatRoomService.java
  src/main/java/com/tickettogether/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/tickettogether/global/config/security/SecurityConfig.java
  src/main/java/com/tickettogether/global/config/security/exception/TokenEmptyException.java
  src/main/java/com/tickettogether/global/config/security/jwt/filter/TokenAuthenticationFilter.java
  src/main/java/com/tickettogether/global/config/security/utils/HeaderUtil.java
  src/main/java/com/tickettogether/global/error/ErrorCode.java
  src/main/resources/templates/Room.html
Labels: 🛠 리팩토링

#183 :recycle: 모든 컨트롤러 로그인 연동
  src/main/java/com/tickettogether/domain/calendar/controller/CalendarControllerV1.java
  src/main/java/com/tickettogether/domain/culture/controller/CultureController.java
  src/main/java/com/tickettogether/domain/parts/controller/PartsController.java
  src/main/java/com/tickettogether/domain/reservation/controller/ReservationController.java
  src/main/java/com/tickettogether/domain/review/controller/ReviewController.java
  src/main/java/com/tickettogether/global/config/security/SecurityConfig.java
Labels: 🛠 리팩토링
